### ISSUE TITLE
W/O admin requirment 

### ISSUE THREAD

**Issue by khalifa23968** [Decicus/discord-server-change#1]
what would i have to chnage to make it that anyone can change the server region?

**Comment by Decicus** [comment]
Sorry for the late reply.

The easiest would be to change [line 48 in `index.js`](https://github.com/Decicus/discord-server-change/blob/master/index.js#L48).

From: `return member.hasPermission(Permissions.MANAGE_GUILD, options);`
To: `return true;`

This will allow **everyone in the server** to change server region.

EDIT: Accidentally closed the issue.

I think this might be a good idea to have a configuration option for, something like: `allowEveryoneToChangeRegion` in `config.js`. I'll take a look at it at some point in the future.
