### ISSUE TITLE
Error updating region.

### ISSUE THREAD

**Issue by Raedista** [Decicus/discord-server-change#10]
Hello,
I'm using Server Changer [Everyone]
There is a problem happen with &eu (europe) command only: Error updating region.
The rest of commands working fine.

**Comment by Decicus** [comment]
Looks like they just got rid of a bunch of regions

```
- US West [us-west]
- Brazil [brazil]
- Hong Kong [hongkong]
- India [india]
- Japan [japan]
- Rotterdam [rotterdam]
- Russia [russia]
- Singapore [singapore]
- South Africa [southafrica]
- Sydney [sydney]
- US Central [us-central]
- US East [us-east]
- US South [us-south]
```

Rotterdam would be the best option for EU, so you'll have to use `!v rotterdam` for the time being until I've gotten around to fixing it.
