### ISSUE TITLE
please add "Discord.allowEveryoneToMoveRegion" feature to public bot.

### ISSUE THREAD

**Issue by Raedista** [Decicus/discord-server-change#8]
I don't know how to set up or host the bot by myself.

please add "Discord.allowEveryoneToMoveRegion" feature to public bot.

so I can choose true or false by commands.

**Comment by Decicus** [comment]
I [mentioned in issue #6](https://github.com/Decicus/discord-server-change/issues/6#issuecomment-855326476) that I didn't want to do something like this (and my reasoning) and rather just have a separate bot that has that setting enabled and I intend to stick with that.

I've now set up the second bot that has `allowEveryoneToMoveRegion` enabled and if you'd like you can invite that bot to your server and kick the other one: https://github.com/Decicus/discord-server-change#add-to-your-server

**Comment by Raedista** [comment]
That's all I want.. Thank you very much, you are awesome :) saved my life.

‫في السبت، 26 يونيو 2021 في 4:25 م تمت كتابة ما يلي بواسطة ‪Alex
Thomassen‬‏ ***@***.***‬‏>:‬
